### ISSUE TITLE
Reduce repetition in `try_process_group_by_unnest` and  `try_process_unnest`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11498]
> This function seems to have some code repetition with function [try_process_unnest](https://github.com/apache/datafusion/blob/f204869ff55bb3e39cf23fc0a34ebd5021e6773f/datafusion/sql/src/select.rs#L295). 

I wonder if there's a better way to handle this, such as planning unnest before aggregation, and then reusing the current group-by planning logic. This seems more intuitive to me. But I'm not sure about it.

_Originally posted by @jonahgao in https://github.com/apache/datafusion/pull/11469#discussion_r1678992594_

The idea is to remove the repetition, and possibly also this comment as well: https://github.com/apache/datafusion/pull/11469/files#r1678995060 

> If unnest has already been processed by try_process_aggregate_unnest, does the following logic for handling unnest become redundant?

**Comment by JasonLi-cn** [comment]
take

**Comment by JasonLi-cn** [comment]
After testing, it is found that the following logic is necessary even if the unnest has been processed by `try_process_aggregate_unnest`. Because `try_process_aggregate_unnest` deals with unnest in the Aggregate's input, and **the following logic** deals with unnest in `select_exprs`, which is downstream of the Aggregate.
