### ISSUE TITLE
Resources exhausted errors are confusing return the biggest memory consumers.

### ISSUE THREAD

**Issue by wiedld** [apache/datafusion#11523]
### Is your feature request related to a problem or challenge?

When asking for more memory via the [memory reservation](https://github.com/apache/datafusion/blob/b0925c801e1c07bd78c78b045ab58fbd0630b638/datafusion/execution/src/memory_pool/mod.rs#L186), the [error returned from the underlying memory pool](https://github.com/apache/datafusion/blob/b0925c801e1c07bd78c78b045ab58fbd0630b638/datafusion/execution/src/memory_pool/pool.rs#L235-L240) focuses on that specific request. As a result, when debugging a resource exhausted error, we get an error message that looks something like:
```
Failed to allocate additional 795696944 bytes for RepartitionExec[1]
with 3182787776 bytes already allocated - 
maximum available is 63296515
```

This^^ error is about what next incremental request failed to get more memory, and **not about what is using the most memory**. As a result, additional dev time has to be spent to (a) at best, track down the actual high memory consumer and (b) at worst, wasted time chasing the wrong memory consumer.
 

### Describe the solution you'd like

One possible solution is to have the error message returned the Top K memory consumers.

**Comment by alamb** [comment]
I agree this message is quite confusing

There is a related idea here I think https://github.com/apache/datafusion/issues/6934

I think @westonpace  mentioned something similar when they were debugging OOM issues too

**Comment by comphead** [comment]
The message is quite confusing and we can probably make it better, mentioning requested, used, allocated and remaining mem. But I'm not sure if there is an easy way to what takes the mem, as memory reservation has no idea about the caller just the mem pool name.

**Comment by wiedld** [comment]
> The message is quite confusing and we can probably make it better, mentioning requested, used, allocated and remaining mem. But I'm not sure if there is an easy way to what takes the mem, as memory reservation has no idea about the caller just the mem pool name.

Well timed comment @comphead . I was just linking a previous (closed) PR which started down the path of tracking memory consumers (for the purposes of debug dumping). I'm not proposing that as the solution per se, rather giving us an idea of prior work.

**Comment by alamb** [comment]
I believe @wiedld  plans to look at this one later this week. We have seen it with our customers and it is quite confusing.

**Comment by alamb** [comment]
@wiedld has an initial PR to  add `TrackedMemoryPool` in https://github.com/apache/datafusion/pull/11665

Here is my proposal for what remains to close this issue
- [ ] Improving the default error message
- [ ] Using the `TrackConsumersPool` as the default memory pool 

# Thoughts on error messages

Message today:

> Failed to allocate additional {} bytes for {} with {} bytes already allocated - maximum available is {}

@wiedld 's proposal on https://github.com/apache/datafusion/pull/11665/files#r1693465283

> Failed to allocate additional {} bytes for {} with {} bytes already allocated for this reservation - {} bytes remain available for the total pool

I think the new proposal is better as it is clearer what is going on

# Thoughts on changing the default pool

The the default is set here: https://github.com/apache/datafusion/blob/89677ae66ec2238ffd58de8c36fe6030fad458fa/datafusion/execution/src/runtime_env.rs#L211

I believe we should change the default pool in DataFusion to be a `TrackedMemoryPool<GreedyMemoryPool>` otherwise the error messages when a memory limit will continue to have the issues that are described in this tickets. 

The only potential issue with changing the default is that the tracking has some additional runtime overhead -- therefore we should run benchmark tests to ensure there is no performance regression. 

Also, a nice part of @wiedld 's `TrackedMemoryPool` design is that someone finds the overhead to be too large, they can change back to the existing `GreedyMemoryPool`
