### ISSUE TITLE
crates.io page has broken logo

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#13526]
### Describe the bug

https://crates.io/crates/datafusion/43.0.0 apache datafusion logo is missing

![Screenshot 2024-11-22 at 9 58 38 AM](https://github.com/user-attachments/assets/5042b643-835e-40fd-acb4-cc03729712c2)

### To Reproduce

not sure

### Expected behavior

The logo should be like https://datafusion.apache.org/

![Screenshot 2024-11-22 at 10 00 20 AM](https://github.com/user-attachments/assets/21d0b16c-f2be-44e1-aa64-5696eeeb629f)

**Comment by Eason0729** [comment]
> `https://github.com/apache/datafusion/raw/HEAD/datafusion/core/docs/source/_static/images/2x_bgwhite_original.png` was found in crate.io.
> `https://github.com/apache/datafusion/raw/HEAD/docs/source/_static/images/2x_bgwhite_original.png` is the correct one.

The logo is missing because `readme = "../../README.md"` in `datafusion/core/Cargo.toml`.

If image `./static/image.png` was specified, in this case crates.io resolve path to `datafusion/core/static/image.png`, but `static/image.png` is what we would like is `static/image.png`

Possible solution:
1. use absolute path
2. maintain a separate README.md for crate.io(create `datafusion/core/README.md` and `readme = "./README.md"`)

I prefer first one, and I could open a PR if you agree.

Also, I thinks it's an good first issue, so I can also leave it to other if missing logo is not an serious problem

**Comment by alamb** [comment]
> I prefer first one, and I could open a PR if you agree.

I agree. Thank you 🐰 

> Also, I thinks it's an good first issue, so I can also leave it to other if missing logo is not an serious problem

Good call -- I added the tag. I defer to you if you want to fix it.

**Comment by A-JM** [comment]
take
