### ISSUE TITLE
Downloading IMDB dataset for benchmarks gives 404 Not Found

### ISSUE THREAD

**Issue by alihan-synnada** [apache/datafusion#13896]
### Describe the bug

Attempting to download the IMDB dataset gives the following error:

```
tar: Error opening archive: Unrecognized archive format
```

An `IMDB.tgz` is created with the following content:

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>
```

It seems the dataset is removed or unavailable.

### To Reproduce

Run `benchmarks/bench.sh data imdb`

### Expected behavior

It should download the dataset, extract the csv files and convert to parquet.

### Additional context

The related part in `bench.sh`
https://github.com/apache/datafusion/blob/6cfd1cf1e030ccfe3b17621cc51fdcefcceae018/benchmarks/bench.sh#L458-L463

**Comment by Spaarsh** [comment]
@alihan-synnada This is more of an issue on the the CWI website. I went to the http://homepages.cwi.nl/~boncz/job/ URL (removing the last part of the url in the code), and found the imdb.tgz dataset link. Upon hovering over it, I came across the link that actually hosts the data: https://event.cwi.nl/da/job/imdb.tgz

I changed the url in the script [here](https://github.com/apache/datafusion/blob/6cfd1cf1e030ccfe3b17621cc51fdcefcceae018/benchmarks/bench.sh#L463) and now the code works as expected:
![20241225_001005](https://github.com/user-attachments/assets/4ff8020c-8bae-4e2d-9c03-1b28a933426b)

If this is an acceptable solution, I will make a PR.

Here is the content of the page displayed at http://homepages.cwi.nl/~boncz/job/ (note that even the protocol is wrong, maybe due to changes in the host website, it should be https), notice the imdb.tgz at the bottom:
![image](https://github.com/user-attachments/assets/1562223a-4917-4d8a-8c7f-857ee19767d1)

**Comment by alihan-synnada** [comment]
@Spaarsh Nice find! It works for me too. I think you can open the PR and hopefully it will be merged without much delay.

**Comment by Spaarsh** [comment]
Done! Thanks! I came across an interesting thing. While reproducing the bug, the HTML response file had been stored at the same path /data/imdb as the original file was intended to. So when i ran the command again after making the changes, I had to manually remove that file since I was getting the "file already exists" error. I suppose these kind of commands ought to be atomic? So that in case of failure, all actions are rolled back? Should I open an issue for this?

**Comment by alihan-synnada** [comment]
@Spaarsh Good catch. I'm not sure what the best approach be since deleting is a destructive operation. We can either prevent the creation of a bad file in the first place (e.g., by verifying its MD5 hash after downloading) and keep the "file already exists" error, or prompt the user for an overwrite if a file exists. I don't know how to do either in bash but I guess you could add it to the PR if it's a simple fix. Otherwise another issue would be great 👍

**Comment by berkaysynnada** [comment]
> @Spaarsh Good catch. I'm not sure what the best approach be since deleting is a destructive operation. We can either prevent the creation of a bad file in the first place (e.g., by verifying its MD5 hash after downloading) and keep the "file already exists" error, or prompt the user for an overwrite if a file exists. I don't know how to do either in bash but I guess you could add it to the PR if it's a simple fix. Otherwise another issue would be great 👍

@Spaarsh do you plan to work on @alihan-synnada suggestions?

**Comment by Spaarsh** [comment]
> > @Spaarsh Good catch. I'm not sure what the best approach be since deleting is a destructive operation. We can either prevent the creation of a bad file in the first place (e.g., by verifying its MD5 hash after downloading) and keep the "file already exists" error, or prompt the user for an overwrite if a file exists. I don't know how to do either in bash but I guess you could add it to the PR if it's a simple fix. Otherwise another issue would be great 👍
> 
> @Spaarsh do you plan to work on @alihan-synnada suggestions?

Sure! I do have a different approach though. Before the file is not entirely downloaded, it can be named something similar to imdb.tmp.tgz. If any error occurs, we purge the file before exiting. If no errors are encountered, change the filename to the intended one.

**Comment by alamb** [comment]
> I think git also uses a similar mechanism while cloning a repo. I'll look into its details and show my findings here.

💯  makes a lot of sense

**Comment by Spaarsh** [comment]
Okay so I went through the code of git clone command [here](https://github.com/git/git/blob/76cf4f61c87855ebf0784b88aaf737d6b09f504b/builtin/clone.c). I also ran the command and did ```ls``` mid run, revealing that it had made the repo with the original name. When I cancelled the clone command, it simply removed all the contents and the directory as well. The git clone source code has a [```remove_junk``` function](https://github.com/git/git/blob/76cf4f61c87855ebf0784b88aaf737d6b09f504b/builtin/clone.c#L470) for this purpose. And just to clarify, the removal of a downloaded file shall be done only in case of an error or exception since those files won't be usable anyway.

I was wondering if there might me similar instances in other parts of our code? Should I make a PR for making this action atomic?

**Comment by alamb** [comment]
> I was wondering if there might me similar instances in other parts of our code? Should I make a PR for making this action atomic?

Making downloads atomic in bench.sh seems like a good improvement to me (as it will prevent issues due to potentially large downloads being interrupted causing confusion)

Not sure about other areas in the code

**Comment by Spaarsh** [comment]
I have worked a bit on these lines. I have also added traps that ensure that cleanup takes place if the user interrupts the downloads intentionally as well. Trying to apply it to other functions as well now. The output is this so far:
#### For the benchmarks/bench.sh data imdb command:
![20241230_012510](https://github.com/user-attachments/assets/a61058b2-7cb3-4aa7-8b6f-1b7b9de0b9cc)

#### For the benchmarks/bench.sh data clickbench_1 command:
![20241230_012240](https://github.com/user-attachments/assets/4dc12987-a73c-4632-974b-a52bd434cdf3)

If this looks good enough, should open an issue for this and make a PR? Or directly open a PR?
I have pushed this code to my fork [here](https://github.com/apache/datafusion/commit/f558cd9210b0dddedd9ff4f8f97dbc510e22d9e5). Suggestions are welcome!

Thanks!
