### ISSUE TITLE
Support optional filter in SortMergeJoin

### ISSUE THREAD

**Issue by yjshen** [apache/datafusion#2628]
Align SortMergeJoin with HashJoin for the optional filter support. Based on the efforts in #2509

**Comment by korowa** [comment]
I've tried to do some POC with constructing intermediate batch and applying filter to it while `freeze_buffered_join_streamed` -- it seems to be the only place where filtering required, and noticed (please correct me, if I'm mistaken), that due to `freeze_*` functions logic, output ordering can be broken in case of outer joins -- while freezing, joined and non-joined records from outer table append as separate batches, and after that no merges / resorts happen -- just batch concatenation.

I suppose output ordering to be quite important for planning (i.e. if we had merge/stream/pipe aggregate operator it could be planned over merge join output), so I wonder - shouldn't this be fixed prior to MJ filter? I guess this fix could significantly change MJ logic in places where filtering required 🤔 

@yjshen , @richox what do you think of it?

**Comment by Dandandan** [comment]
AFAIK closed by https://github.com/apache/datafusion/pull/9080
