### ISSUE TITLE
Use a single HashMap implementation consistently across the code base

### ISSUE THREAD

**Issue by houqp** [apache/datafusion#677]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

We are using both `std::collections::HashMap` and `hashbrown::HashMap` in datafusion, it would be better to consistently use only one of them.

hashbrown's official readme has the following statement:

> Since Rust 1.36, this is now the HashMap implementation for the Rust standard library. However you may still want to use this crate instead since it works in environments without std, such as embedded systems and kernels.

However, it's unclear whether Rust std also uses ahash as the default hasher. If not, it seems like hashbrown would still be a better choice when it comes to performance.

**Describe alternatives you've considered**

**Additional context**

Follow up from https://github.com/apache/arrow-datafusion/pull/676#discussion_r663544711.

**Comment by Dandandan** [comment]
The hash brown crate is used 

* It exposes some more APIs like `RawEntry`, which can avoid hashing / looking up elements twice.
* It is slightly faster than the version included with Rust std, not only because of aHash (vs SipHasher used in std), but also some further optimizations / inlining.

I think best would be to define a `HashMap` type alias, so we can use whatever is set by default across the project.

**Comment by houqp** [comment]
Agreed, I think we should move all HashMap import to our own pluggable type alias and set `hashbrown::HashMap` as the default.

**Comment by alamb** [comment]
`hashbrown::HashMap` is a good choice 👍 in my opinion
