### ISSUE TITLE
Refactor the hash_aggregate

### ISSUE THREAD

**Issue by sundy-li** [apache/datafusion#839]
`hash_aggregate` is using `compute::take` to split the columns into lots of small columns.  This is the main reason why `hash_aggregate` works slow.  It'll be slower if the indices are more dispersed (more keys).

https://github.com/apache/arrow-datafusion/blob/4ddd2f5e7582ffe662aea27bbb74c58cd0715152/datafusion/src/physical_plan/hash_aggregate.rs#L422-L438

**Comment by Dandandan** [comment]
You are right that the current hash aggregate is quite a bit slower in this case than it should be.

There is some work already by @alamb to make the hash aggregate faster for smaller keys and already gives a ~2x speedup on a tougher query.
https://github.com/apache/arrow-datafusion/issues/790

I don't think the slow code is in the code you quoted, the `take` is only done once for each input array. The slower part just below though works on each new input key + input array and does e.g. `slice` on it which has a high overhead because of that.
There are some ideas linked in the issue to deal with that.

There are currently also some other parts in the code that are even contributing more to the runtime, such as materializing the end keys/states to an array.

**Comment by sundy-li** [comment]
>  the take is only done once for each input array.

It's done to the entire record batches. Considering the batches are 1024 rows with 3 columns, if the key number is 256,  then there will be 256 small batches after the take. `Simd` will make no sense in this situation.

> materializing the end keys/states to an array.

Yes, this may be a good point to go.

**Comment by Dandandan** [comment]
> It's done to the entire record batches. Considering the batches are 1024 rows with 3 columns, if the key number is 256, then there will be 256 small batches after the take, each batch is about 4 rows. `Simd` will make no sense in this situation.
> 
> >

Yes, but not in the code you linked. There the `take` is done once for the arrays in `aggr_input_values`, regardless of how many distinct keys we have in the batch. The take only rearranges the data to be in the same order as the keys but does it for only once for each input array for the aggregate expression values (not even the entire batch).

In other places, yes, operations like `Array::slice` are done for each key that occurred which starts to become inefficient when having a lot of small groups in the batch and also show up in profiles.

**Comment by alamb** [comment]
FWIW I believe @jhorstmann  also had some thoughts in this area (aka on the use of `take` vs some other ways to speed up the distinct calculation) in https://github.com/apache/arrow-datafusion/issues/790#issuecomment-888591358 which may be related to this conversation

**Comment by drauschenbach** [comment]
If I'm reading the code correctly, this specific reference to code no longer exists.

**Comment by andygrove** [comment]
Closing this. Thanks @drauschenbach.
